apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-deployment
    labels:
      tier: frontend
spec:
  replicas: 4   # ✅ Moved replicas above template for clarity
  selector:
    matchLabels:
      app: nginx   # ✅ Must exactly match template.metadata.labels
      tier: frontend

  template:
    metadata:
      labels:  # ✅ Removed `name: nginx` (not needed)
        app: nginx
        tier: frontend

    spec:
      containers:
        - name: nginx
          image: nginx

